---
- id: shfmt
  name: Format bash shell scripts
  description: Format bash scripts to a canonical format using the shfmt tool.
  entry: hooks/shfmt.sh
  language: script
  types: [shell]
  # Default options to list files changed and write changes to files
  args: ["-l", "-w"]
